data:
  data_platform: local
  account_name: 'skurt'
  production: False
  aggregations:
    sales_quantity: mean
profiling:
  profiling_group_cols: ['product_hierarchy_1_desc', 'product_hierarchy_2_desc']
  sales_profiling_gap: [0.25, 2]
  profiling_month: 12
  feature_engineering:
    daily_agg_level:
      historic_sales_features:
        shifts: [1, 2, 3, 4, 5, 6, 7]
  clustering:
    date_start: 2022-01-01 
       